language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: EdSsXwQEYMWfV6a734js6p3WR13AytmskHYokTQwMfn4z35zB4Ft90LwPJ2LkdMd65I0FUomAwqt5R88fvt6haXwqf2omZuTsV79HfPRPUVFchRUjHQ/2eSvnjCHEPzDAwAi+m5RKpqv+YU/audNtkRhs+tm1YAkIXIFgtin0AwSANiqUhI889bjCeanUeFqbvFlXwYpLk9jt3icR/fBhPlQxQb2C56Ko/PtFlWMZ4EIGoA7xnDQM+M8ouLAiKFKxvrD1dxHXSoXGSiPPDmc9NChAmXzo6yKVo7KooQZHdtILU+s2eHwUuWXFQZCZlXTjEAOP5fFlu6FZvCTPEJV1Q7QzZeN1re/hkCqhLPBAk7r4j2I+KXnmqLrAJ9jM7Y0HQgTq+bEEoZnK5e+EhnXjQ9qFmySqAZM9byH3jm1b4m62+5dgct0IFq/NhYOpwao6doK2j3yffbJ3a9o7RLLUygJFpJKgTyOB8Abcqciix6vGEaF4qbRXhfWTzAoArJClUJDHibqpuCSUPAhVrpu4OYjAryniJAD0zwOL6aqEyDjzYmPEmTk4EGSS7YRgLnIryXf4REhtJ69GouPKGMin+QMrPRmUN1bAF+w3q1k3p3tlKMPYhrj0SdP601eID0pHzgm/OHcC6amFSKbfT92qXHaKCXa5v84xnIXG9c/8Lg=
